#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <ctype.h>

#include "ldpasswd/ldpasswd.h"
#include "ldpasswd/data.h"

// Match the Python struct format exactly
#pragma pack(push, 1)
typedef struct {
    char token[2];    // The 1 or 2 char string
    char is_word;     // 1 if this node completes a valid word
    char padding;     // Alignment byte
    int child_idx;    // Offset in the array where children start
    int child_cnt;    // Number of children at that offset
} Node;
#pragma pack(pop)

// These are generated by xxd -i data.bin
extern unsigned char data_bin[];
extern unsigned int data_bin_len;

// Standard comparator for binary search on the token field
int compare_nodes(const void *a, const void *b) {
    Node *nodeA = (Node *)a;
    Node *nodeB = (Node *)b;
    // We use strncmp to safely compare up to 2 characters
    return strncmp(nodeA->token, nodeB->token, 2);
}

// Structure to hold the results of un-leeting a password
typedef struct {
    char **strings;
    int count;
    int capacity;
} ResultList;

// Simple structure to map leet chars back to letters
typedef struct {
    char leet;
    char original;
} Map;

// Map for Leetspeak substitutions.
Map LEET_MAP[] = {
    {'4', 'a'}, {'@', 'a'}, {'8', 'b'}, {'(', 'c'}, {'{', 'c'}, 
    {'[', 'c'}, {'<', 'c'}, {'3', 'e'}, {'6', 'g'}, {'9', 'g'}, 
    {'1', 'i'}, {'!', 'i'}, {'|', 'i'}, {'1', 'l'}, {'|', 'l'}, 
    {'7', 'l'}, {'0', 'o'}, {'$', 's'}, {'5', 's'}, {'+', 't'}, 
    {'7', 't'}, {'%', 'x'}, {'2', 'z'}
};

void add_result(ResultList *res, const char *str) {
    if (res->count == res->capacity) {
        res->capacity *= 2;
        res->strings = realloc(res->strings, sizeof(char*) * res->capacity);
    }
    res->strings[res->count++] = strdup(str);
}


/**
 * The following two functions (backtrack and generate_unleet) are utilized to generate all possible "un-leeted" versions of a given password.
 * Example: "p@ssw0rd" would generate "password", "p@ssword", "passw0rd", etc.
 * 
 * There are 2 functions because recursion is used
 */
void backtrack(const char *input, char *current, int index, ResultList *res) {
    if (input[index] == '\0') {
        current[index] = '\0';
        add_result(res, current);
        return;
    }

    char c = input[index];
    int found = 0;

    // Check the map for all possible translations
    for (int i = 0; i < sizeof(LEET_MAP) / sizeof(Map); i++) {
        if (LEET_MAP[i].leet == c) {
            found = 1;
            current[index] = LEET_MAP[i].original;
            backtrack(input, current, index + 1, res);
        }
    }

    // Also consider the character as itself (e.g., '0' stays '0')
    current[index] = c;
    backtrack(input, current, index + 1, res);
}

ResultList generate_unleet(const char *input) {
    ResultList res;
    res.count = 0;
    res.capacity = 10;
    res.strings = malloc(sizeof(char*) * res.capacity);
    
    char *buffer = malloc(strlen(input) + 1);
    backtrack(input, buffer, 0, &res);
    free(buffer);
    
    return res;
}

/**
 * Returns the deepest index where a valid word was found, or 0 if no word was found at all.
 */
int find_word(const char *pw) {
    // These variables define the current search state in the trie
    // root_idx and root_cnt are the starting point for the search (the top-level nodes)
    int root_idx = 0;
    int root_cnt = 678;

    // The data_bin array is a flat representation of the trie nodes. We cast it to our Node struct for easier access.
    Node *table = (Node *)data_bin;

    // p_idx tracks our position in the input password string.
    int p_idx = 0;

    // current_idx and current_cnt define the current range of nodes we're searching through.
    int current_idx = root_idx;
    int current_cnt = root_cnt;

    // current_depth tracks how deep we are in the trie
    int current_depth = 0;

    // last_valid_depth remembers the deepest valid word we've found so far.
    int last_valid_depth = 0;
    int pw_len = strlen(pw);

    // Iterate through the characters in the password, trying to match tokens in the trie.
    // We attempt to consume 2 characters at a time, but if that fails, we fall back to 1 character.
    
    // This is equal to 1 or 2 based on the end of the word
    int chars_to_consume = 0;

    while (p_idx < pw_len) {
        Node key = {0};
        chars_to_consume = 0;

        // Try a 2-character token first
        if (p_idx + 1 < pw_len) {
            key.token[0] = pw[p_idx];
            key.token[1] = pw[p_idx + 1];
            chars_to_consume = 2;
        } else {
            // Only 1 char left in password
            key.token[0] = pw[p_idx];
            key.token[1] = '\0';
            chars_to_consume = 1;
        }

        // Search the current sibling range
        Node *match = bsearch(&key, &table[current_idx], current_cnt, sizeof(Node), compare_nodes);

        // If 2-char failed (and we had 2 chars), try the 1-char fallback
        if (!match && chars_to_consume == 2) {
            key.token[1] = '\0';
            match = bsearch(&key, &table[current_idx], current_cnt, sizeof(Node), compare_nodes);
            if (match) chars_to_consume = 1;
        }

        if (match) {
            current_depth++;
            p_idx += chars_to_consume;

            // Update our "last known good" if this node is a word terminator
            if (match->is_word) {
                last_valid_depth = current_depth;
            }

            // If there are no children, we can't go deeper
            if (match->child_idx == -1 || match->child_cnt == 0) {
                break;
            }

            // Move to the next level of the tree
            current_idx = match->child_idx;
            current_cnt = match->child_cnt;
        } else {
            // Chain broken; no more matches in the tree
            break;
        }
    }
    // Return the length of the word
    if (chars_to_consume == 2) {
        return last_valid_depth * 2;
    } else {
        return last_valid_depth * 2 - 1;
    }
}


/**
 * Tokenizes the password into an array of tokens, where each token is either a word, a number, or a special character.
 * The start indices of each token in the original password are stored in the start_of_token_indicies array, 
 * and the type of each token is stored in the token_types array (word, number, special, or other).
 */
int tokenize_password(const char *pw, int *start_of_token_indicies, char *token_types) {
    // First get the length of the password
    int pw_length = strlen(pw);

    // Create an array with all leatspeakable versions of the word
    char* lower_password;
    lower_password = malloc(pw_length + 1);
    strncpy(lower_password, pw, pw_length + 1); 
    for (int j = 0; lower_password[j]; j++) {
        lower_password[j] = tolower(lower_password[j]);
    }

    ResultList results = generate_unleet(lower_password);
    free(lower_password);

    int token_count = 0;

    // Now iterate through the password and find all tokens

    for (int i = 0; i < pw_length; i++) {
        // Only storing 20 tokens
        if (token_count >= 20) {
            break;
        } else {
            start_of_token_indicies[token_count] = i;
            token_count++;
        }

        // Start by trying to find a word
        // We'll check for a word starting at i in each of the 
        // un-leeted versions of the password, and take the longest match
        int max_word_len = 0;
        int word_len = 0;
        for (int j = 0; j < results.count; j++) {
            word_len = find_word(results.strings[j] + i);
            if (word_len > max_word_len) {
                max_word_len = word_len;
            }

        }
        // If we have a word 1 or 2 characters in length
        // And one of them is not a-zA-z, then its safe to assume that it's not actually
        // leetspeak, and a false positive, so set max_word_len to 0 to ignore it as word.
        if (max_word_len == 1) {
            if (!((pw[i] >= 'a' && pw[i] <= 'z') || (pw[i] >= 'A' && pw[i] <= 'Z'))) {
                max_word_len = 0;
            }
        } 
        if (max_word_len == 2) {
            if (!((pw[i + 1] >= 'a' && pw[i + 1] <= 'z') || (pw[i + 1] >= 'A' && pw[i + 1] <= 'Z'))) {
                max_word_len = 0;
            }
        }
        // This means we found a word
        // The check is > 1, because if we think we found a single character word
        // (ex. A, I, S, etc.) we want to ignore that because it for now, because the leet
        // speak check mightve accidently caught that. For axample, it could be 45, and we would
        // rather tokenize the whole number togheter, instead of just the letter. If all of our checks
        // fail, then we just tokenize a single character, so it really doesn't make a difference
        // by the end of the process, but this way we will catch number combinations.
        if (max_word_len > 0) {
            token_types[token_count - 1] = 'w'; // 'w' for word
        }
        if (max_word_len > 1) {
            i += max_word_len - 1; // -1 because the loop will increment i again
        }

        // Next check if we have a number
        else if (pw[i] >= '0' && pw[i] <= '9') {
            token_types[token_count - 1] = 'n'; // 'n' for number
            for (int j = i + 1; j < pw_length; j++) {
                // figure out if we have a number after
                // If not, break out of the 'j' loop.
                if (pw[j] < '0' || pw[j] > '9') {
                    break;
                } else {
                    // If we do, increment i again to skip over the number
                    // because that gets counted with the previous token.
                    i = j;
                }
            }
        }
        // Next check if we have a special character.
        // No need to check for any other special characters after,
        // they should each be treated as their own token
        else if ((pw[i] >= '!' && pw[i] <= '/') || (pw[i] >= ':' && pw[i] <= '@') || (pw[i] >= '[' && pw[i] <= '`') || (pw[i] >= '{' && pw[i] <= '~')) {
            token_types[token_count - 1] = 's'; // 's' for special character
        } else {
            token_types[token_count - 1] = 'o'; // 'o' for other
        }
    }

    // Cleanup
    for (int i = 0; i < results.count; i++) {
        free(results.strings[i]);
    }
    free(results.strings);

    return 1;
}

void hello() {
    const char *test_pws[] = {
        "Password",
        "pass",
        "PassWord123",
        "Unknownword",
        "james",
        "jamesblahblahblah",
        "P@sSw0Rd",
        "Password7JamesTh1ngFather",
        "passw0rdRed14&TeamSucks",
        "123PassWord123",
        "1Unknown(((wordBlah",
        "jameswaoifjwa",
        "12!Blah!21",
        "P@sSw0RdJ4mes"
    };

    for (int i = 0; i < 14; i++) {
        // Array to hold starting indices of each token
        int *start_of_token_indicies = malloc(20 * sizeof(int));
        for (int i = 0; i < 20; i++) {
            start_of_token_indicies[i] = -1;
        }
        int token_count = 0;

        // Array to hold type of each token (word, number, special, or other)
        char *token_types = malloc(20 * sizeof(char));
        for (int i = 0; i < 20; i++) {
            token_types[i] = '\0';
        }


        printf("Tokenizing: %s\n", test_pws[i]);
        int tokens = tokenize_password(test_pws[i], start_of_token_indicies, token_types);
        for (int j = 0; j < 20; j++) {
            if (start_of_token_indicies[j] != -1) {
                int next_token_start = (j < 19) ? start_of_token_indicies[j + 1] : strlen(test_pws[i]);
                if (token_types[j] == 'w') {
                    printf("Word");
                } else if (token_types[j] == 'n') {
                    printf("Number");
                } else if (token_types[j] == 's') {
                    printf("Special");
                } else {
                    printf("Other");
                }
                printf(":%.*s\n", next_token_start - start_of_token_indicies[j], test_pws[i] + start_of_token_indicies[j]);
                // printf("%d:%c  ", start_of_token_indicies[j], token_types[j]);
            }
        }
        printf("\n");
    }
}