#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#include "ldpasswd/ldpasswd.h"
#include "ldpasswd/data.h"

// Match the Python struct format exactly
#pragma pack(push, 1)
typedef struct {
    char token[2];    // The 1 or 2 char string
    char is_word;     // 1 if this node completes a valid word
    char padding;     // Alignment byte
    int child_idx;    // Offset in the array where children start
    int child_cnt;    // Number of children at that offset
} Node;
#pragma pack(pop)

// These are generated by xxd -i data.bin
extern unsigned char data_bin[];
extern unsigned int data_bin_len;

// Standard comparator for binary search on the token field
int compare_nodes(const void *a, const void *b) {
    Node *nodeA = (Node *)a;
    Node *nodeB = (Node *)b;
    // We use strncmp to safely compare up to 2 characters
    return strncmp(nodeA->token, nodeB->token, 2);
}

/**
 * Returns the deepest index where a valid word was found, or 0 if no word was found at all.
 */
int find_word(const char *pw) {
    // These variables define the current search state in the trie
    // root_idx and root_cnt are the starting point for the search (the top-level nodes)
    int root_idx = 0;
    int root_cnt = 695;

    // The data_bin array is a flat representation of the trie nodes. We cast it to our Node struct for easier access.
    Node *table = (Node *)data_bin;

    // p_idx tracks our position in the input password string.
    int p_idx = 0;

    // current_idx and current_cnt define the current range of nodes we're searching through.
    int current_idx = root_idx;
    int current_cnt = root_cnt;

    // current_depth tracks how deep we are in the trie
    int current_depth = 0;

    // last_valid_depth remembers the deepest valid word we've found so far.
    int last_valid_depth = 0;
    int pw_len = strlen(pw);

    // Iterate through the characters in the password, trying to match tokens in the trie.
    // We attempt to consume 2 characters at a time, but if that fails, we fall back to 1 character.
    
    // This is equal to 1 or 2 based on the end of the word
    int chars_to_consume = 0;

    while (p_idx < pw_len) {
        Node key = {0};
        chars_to_consume = 0;

        // Try a 2-character token first
        if (p_idx + 1 < pw_len) {
            key.token[0] = pw[p_idx];
            key.token[1] = pw[p_idx + 1];
            chars_to_consume = 2;
        } else {
            // Only 1 char left in password
            key.token[0] = pw[p_idx];
            key.token[1] = '\0';
            chars_to_consume = 1;
        }

        // Search the current sibling range
        Node *match = bsearch(&key, &table[current_idx], current_cnt, sizeof(Node), compare_nodes);

        // If 2-char failed (and we had 2 chars), try the 1-char fallback
        if (!match && chars_to_consume == 2) {
            key.token[1] = '\0';
            match = bsearch(&key, &table[current_idx], current_cnt, sizeof(Node), compare_nodes);
            if (match) chars_to_consume = 1;
        }

        if (match) {
            current_depth++;
            p_idx += chars_to_consume;

            // Update our "last known good" if this node is a word terminator
            if (match->is_word) {
                last_valid_depth = current_depth;
            }

            // If there are no children, we can't go deeper
            if (match->child_idx == -1 || match->child_cnt == 0) {
                break;
            }

            // Move to the next level of the tree
            current_idx = match->child_idx;
            current_cnt = match->child_cnt;
        } else {
            // Chain broken; no more matches in the tree
            break;
        }
    }
    // Return the length of the word
    if (chars_to_consume == 2) {
        return last_valid_depth * 2;
    } else {
        return last_valid_depth * 2 - 1;
    }
}

void hello() {
    int root_start = 0;
    int root_count = 500;

    const char *test_pws[] = {
        "password",
        "pass",
        "password123",
        "unknownword",
        "james",
        "jamesblahblahblah"
    };

    for (int i = 0; i < 5; i++) {
        int depth = find_word(test_pws[i]);
        if (depth > 0) {
            printf("Found match for '%s' (Ends at token depth %d)\n", test_pws[i], depth);
        } else {
            printf("No match found for '%s'\n", test_pws[i]);
        }
    }

    return 0;
}